### ISSUE TITLE
Refactor unix timestamps

### ISSUE THREAD

**Issue by isaacknjama** [bitsacco/os#47]
Quoting our last discussion:

reconsider the use of unix timestamps in the backend. We should drop  https://github.com/bitsacco/os/blob/d6219a60e23ff2394d176d59baf094076a32972b/proto/shares.proto#L33, and instead return createdAt and updatedAt fields from the db. Here is an example of how we do this in solowallet https://github.com/bitsacco/os/blob/d6219a60e23ff2394d176d59baf094076a32972b/proto/solowallet.proto#L79-L81

**Comment by okjodom** [comment]
closed by #48
